variable "resource_group_name" {
  description = "Owner-created resource group dedicated to the approved BG-014 exercise."
  type        = string
  nullable    = false
}

variable "location" {
  description = "Azure region for the temporary storage account."
  type        = string
  nullable    = false
}

variable "storage_account_name" {
  description = "Per-run unique name generated by the protected workflow."
  type        = string
  nullable    = false

  validation {
    condition     = can(regex("^bg[0-9]{1,17}x[0-9]{1,3}$", var.storage_account_name))
    error_message = "storage_account_name must contain a numeric run ID and attempt separated by 'x'."
  }
}

variable "run_id" {
  description = "GitHub Actions run ID used to identify exercise resources."
  type        = string
  nullable    = false

  validation {
    condition     = can(regex("^[0-9]{1,17}$", var.run_id))
    error_message = "run_id must contain only 1-17 digits."
  }
}

variable "run_attempt" {
  description = "GitHub Actions run attempt used to distinguish reruns."
  type        = string
  nullable    = false

  validation {
    condition     = can(regex("^[0-9]{1,3}$", var.run_attempt))
    error_message = "run_attempt must contain only 1-3 digits."
  }
}
